import type { ArtPreviewItem, HeroOrbitNode } from './hero.types'
import { lucideInterestIcons } from '../icons/lucideInterestIcons'

export const artPreviewItems = [
   {
      src: 'https://images.unsplash.com/photo-1764025721609-2bd1cf185f32?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      alt: 'Madeira',
      badge: 'LANDSCAPE',
      title: 'Madeira Cliffs',
      description: 'Clouds wrapping the ridge before the sun opened the valley.',
   },
   {
      src: '/images/me.jpg',
      alt: 'Portrait photography',
      badge: 'PORTRAIT',
      title: 'Landing Path',
      description: 'A quiet frame under the flight line with the city opening behind.',
   },
   {
      src: 'https://images.unsplash.com/photo-1761671955448-f68ca9eec238?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1035',
      alt: 'Urban photography',
      badge: 'VALLEY',
      title: 'Blue Valley',
      description: 'A clear mountain basin with the horizon holding just one color.',
   },
   {
      src: 'https://images.unsplash.com/photo-1761671955479-c1fa3e1cf1a8?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1035',
      alt: 'Street photography',
      badge: 'STREET',
      title: 'Flag Street',
      description: 'A narrow corridor of facades, cables and banners in late light.',
   },
   {
      src: 'https://images.unsplash.com/photo-1767279265177-60b3595c61b5?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      alt: 'Lake Ohrid',
      badge: 'SEA',
      title: 'Sail Line',
      description: 'A single mast crossing the calmest part of the afternoon sea.',
   },
   {
      src: 'https://images.unsplash.com/photo-1764181582237-0c57598f693a?q=80&w=1036&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      alt: 'Landscape photography',
      badge: 'RIDGE',
      title: 'Green Rise',
      description: 'A softer slope where clouds break just above the tree line.',
   },
   {
      src: 'https://images.unsplash.com/photo-1759424727859-7f489622313d?q=80&w=967&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      alt: 'Editorial photography',
      badge: 'EDITORIAL',
      title: 'Stone Steps',
      description: 'Texture, repetition and a monochrome path cut into the rock.',
   },
   {
      src: 'https://images.unsplash.com/photo-1759424727855-772a29b2ee93?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      alt: 'Travel photography',
      badge: 'TRAVEL',
      title: 'Harbor Silence',
      description: 'A narrow frame where water and distant relief almost flatten out.',
   },
] as const satisfies readonly ArtPreviewItem[]

export const heroOrbitNodes = [
   {
      key: 'photography',
      kind: 'interest',
      label: 'Fotografia',
      iconSvg: lucideInterestIcons.photography,
      assets: [],
      originKind: 'icon',
      originAssets: [
         {
            src: '/images/figma-color.svg',
            alt: 'Figma',
            className: 'size-6 object-contain',
         },
      ],
      origin: { left: 5.5, top: 29.5 },
      cluster: { left: 22, top: 58, scale: 0.88 },
      clusterMobile: { left: 28, top: 57, scale: 0.76 },
      clusterOffset: { left: -148, top: 50, scale: 0.9 },
      clusterMobileOffset: { left: -96, top: 38, scale: 0.74 },
   },
   {
      key: 'illustration',
      kind: 'interest',
      label: 'Ilustracion',
      iconSvg: lucideInterestIcons.illustration,
      assets: [],
      originKind: 'icon',
      originAssets: [
         {
            src: '/images/convex.svg',
            alt: 'Convex',
            className: 'size-6 object-contain',
         },
      ],
      origin: { left: 28, top: 0 },
      cluster: { left: 28, top: 34, scale: 0.92 },
      clusterMobile: { left: 34, top: 22, scale: 0.78 },
      clusterOffset: { left: -112, top: -72, scale: 0.9 },
      clusterMobileOffset: { left: -70, top: -48, scale: 0.74 },
   },
   {
      key: 'experiments',
      kind: 'interest',
      label: 'Experimentos',
      iconSvg: lucideInterestIcons.experiments,
      assets: [],
      originKind: 'brand-cycle',
      originAssets: [
         {
            src: '/images/codex.svg',
            alt: 'Codex',
            className: 'size-6 object-contain',
         },
         {
            src: '/images/claudecode-color.svg',
            alt: 'Claude Code',
            className: 'size-6 object-contain',
         },
      ],
      origin: { left: 14, top: 50 },
      cluster: { left: 29, top: 5, scale: 0.75 },
      clusterMobile: { left: 84, top: 43, scale: 0.7 },
      clusterOffset: { left: -88, top: -150, scale: 0.78 },
      clusterMobileOffset: { left: -38, top: -104, scale: 0.68 },
   },
   {
      key: 'apps',
      kind: 'interest',
      label: 'Apps',
      iconSvg: lucideInterestIcons.apps,
      assets: [],
      originKind: 'brand-cycle-wide',
      originAssets: [
         {
            src: '/images/gemini-color.svg',
            alt: 'Gemini',
            className: 'size-8 object-contain',
         },
         {
            src: '/images/googlecloud-color.svg',
            alt: 'Google Cloud',
            className: 'size-8 object-contain',
         },
      ],
      origin: { left: 32, top: 84 },
      cluster: { left: 42, top: 16, scale: 1 },
      clusterMobile: { left: 56, top: 14, scale: 0.88 },
      clusterOffset: { left: -18, top: -118, scale: 1 },
      clusterMobileOffset: { left: 0, top: -82, scale: 0.86 },
   },
   {
      key: 'travel',
      kind: 'interest',
      label: 'Viajes',
      iconSvg: lucideInterestIcons.travel,
      assets: [],
      originKind: 'icon',
      originAssets: [
         {
            src: '/images/cloudflare-color.svg',
            alt: 'Cloudflare',
            className: 'size-6 object-contain',
         },
      ],
      origin: { left: 60, top: 8 },
      cluster: { left: 55, top: 0, scale: 0.8 },
      clusterMobile: { left: 71, top: 19, scale: 0.72 },
      clusterOffset: { left: 78, top: -146, scale: 0.82 },
      clusterMobileOffset: { left: 70, top: -96, scale: 0.7 },
   },
   {
      key: 'development',
      kind: 'interest',
      label: 'Desarrollo',
      iconSvg: lucideInterestIcons.development,
      assets: [],
      originKind: 'icon',
      originAssets: [
         {
            src: '/images/vercel.svg',
            alt: 'Vercel',
            className: 'size-3.5 object-contain',
         },
      ],
      origin: { left: 96, top: 41 },
      cluster: { left: 58, top: 30, scale: 1 },
      clusterMobile: { left: 76, top: 37, scale: 0.88 },
      clusterOffset: { left: 112, top: -68, scale: 1 },
      clusterMobileOffset: { left: 90, top: -38, scale: 0.84 },
   },
   {
      key: 'writing',
      kind: 'interest',
      label: 'Notas',
      iconSvg: lucideInterestIcons.writing,
      assets: [],
      originKind: 'icon',
      originAssets: [
         {
            src: '/images/railway.svg',
            alt: 'Railway',
            className: 'size-7 object-contain',
         },
      ],
      origin: { left: 86, top: 61 },
      cluster: { left: 74, top: 39, scale: 0.8 },
      clusterMobile: { left: 20, top: 44, scale: 0.72 },
      clusterOffset: { left: 170, top: -8, scale: 0.82 },
      clusterMobileOffset: { left: -116, top: -6, scale: 0.7 },
   },
   {
      key: 'routes',
      kind: 'interest',
      label: 'Rutas',
      iconSvg: lucideInterestIcons.routes,
      assets: [],
      originKind: 'icon',
      originAssets: [
         {
            src: '/images/googlecloud-color.svg',
            alt: 'Google Cloud',
            className: 'size-6 object-contain',
         },
      ],
      origin: { left: 84, top: 27 },
      cluster: { left: 14, top: 38, scale: 0.65 },
      clusterMobile: { left: 10, top: 31, scale: 0.56 },
      clusterOffset: { left: -205, top: -20, scale: 0.68 },
      clusterMobileOffset: { left: -132, top: -44, scale: 0.58 },
   },
   {
      key: 'video',
      kind: 'interest',
      label: 'Video',
      iconSvg: lucideInterestIcons.video,
      assets: [],
      originKind: 'cover',
      originAssets: [
         {
            src: '/images/logos/procreate.jpeg',
            alt: 'Procreate',
         },
      ],
      origin: { left: 74, top: 98 },
      cluster: { left: 62, top: 54, scale: 0.88 },
      clusterMobile: { left: 57, top: 73, scale: 0.78 },
      clusterOffset: { left: 118, top: 62, scale: 0.9 },
      clusterMobileOffset: { left: 62, top: 70, scale: 0.76 },
   },
] as const satisfies readonly HeroOrbitNode[]
