export const lyrics = {
  segments: [
    {
      text: "If you have food on your plate, clothes on your body and a place to sleep you're richer than 55% of people in the world.",
      words: [
        {
          text: "If",
          start: 0.239,
          end: 0.379,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 0.379,
          end: 0.419,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you",
          start: 0.419,
          end: 0.519,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 0.519,
          end: 0.519,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "have",
          start: 0.519,
          end: 0.74,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 0.74,
          end: 0.759,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "food",
          start: 0.759,
          end: 1.019,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 1.019,
          end: 1.039,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "on",
          start: 1.039,
          end: 1.159,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 1.159,
          end: 1.179,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "your",
          start: 1.179,
          end: 1.279,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 1.279,
          end: 1.36,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "plate,",
          start: 1.36,
          end: 1.759,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 1.759,
          end: 2.019,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "clothes",
          start: 2.019,
          end: 2.479,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 2.479,
          end: 2.5,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "on",
          start: 2.5,
          end: 2.619,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 2.619,
          end: 2.659,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "your",
          start: 2.659,
          end: 2.759,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 2.759,
          end: 2.819,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "body",
          start: 2.819,
          end: 3.179,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 3.179,
          end: 3.659,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "and",
          start: 3.659,
          end: 3.759,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 3.759,
          end: 3.779,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "a",
          start: 3.779,
          end: 3.819,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 3.819,
          end: 3.899,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "place",
          start: 3.899,
          end: 4.159,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 4.159,
          end: 4.219,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "to",
          start: 4.219,
          end: 4.299,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 4.299,
          end: 4.36,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "sleep",
          start: 4.36,
          end: 4.739,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 4.739,
          end: 5.639,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you're",
          start: 5.639,
          end: 5.859,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 5.859,
          end: 5.859,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "richer",
          start: 5.859,
          end: 6.239,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 6.239,
          end: 6.299,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "than",
          start: 6.299,
          end: 6.459,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 6.459,
          end: 6.579,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "55%",
          start: 6.579,
          end: 7.639,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 7.639,
          end: 7.639,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "of",
          start: 7.639,
          end: 7.759,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 7.759,
          end: 7.839,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "people",
          start: 7.839,
          end: 8.14,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 8.14,
          end: 8.159,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "in",
          start: 8.159,
          end: 8.259,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 8.259,
          end: 8.3,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "the",
          start: 8.3,
          end: 8.36,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 8.36,
          end: 8.42,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "world.",
          start: 8.42,
          end: 8.9,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
      ],
    },
    {
      text: " If you have money to spend as you wish and freedom to go anywhere you want you are among the top 8% of the world's population. ",
      words: [
        {
          text: " ",
          start: 8.9,
          end: 9.5,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "If",
          start: 9.5,
          end: 9.619,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 9.619,
          end: 9.659,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you",
          start: 9.659,
          end: 9.759,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 9.759,
          end: 9.819,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "have",
          start: 9.819,
          end: 9.96,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 9.96,
          end: 10.059,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "money",
          start: 10.059,
          end: 10.34,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 10.34,
          end: 10.359,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "to",
          start: 10.359,
          end: 10.46,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 10.46,
          end: 10.539,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "spend",
          start: 10.539,
          end: 10.88,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 10.88,
          end: 10.899,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "as",
          start: 10.899,
          end: 11.039,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 11.039,
          end: 11.079,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you",
          start: 11.079,
          end: 11.159,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 11.159,
          end: 11.239,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "wish",
          start: 11.239,
          end: 11.5,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 11.5,
          end: 11.739,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "and",
          start: 11.739,
          end: 11.88,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 11.88,
          end: 11.96,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "freedom",
          start: 11.96,
          end: 12.379,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 12.379,
          end: 12.399,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "to",
          start: 12.399,
          end: 12.5,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 12.5,
          end: 12.539,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "go",
          start: 12.539,
          end: 12.719,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 12.719,
          end: 12.759,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "anywhere",
          start: 12.759,
          end: 13.159,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 13.159,
          end: 13.219,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you",
          start: 13.219,
          end: 13.3,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 13.3,
          end: 13.359,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "want",
          start: 13.359,
          end: 13.699,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 13.699,
          end: 14.559,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you",
          start: 14.559,
          end: 14.739,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 14.739,
          end: 14.779,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "are",
          start: 14.779,
          end: 14.92,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 14.92,
          end: 15.0,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "among",
          start: 15.0,
          end: 15.239,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 15.239,
          end: 15.299,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "the",
          start: 15.299,
          end: 15.439,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 15.439,
          end: 15.46,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "top",
          start: 15.46,
          end: 15.719,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 15.719,
          end: 15.839,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "8%",
          start: 15.839,
          end: 16.659,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 16.659,
          end: 16.68,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "of",
          start: 16.68,
          end: 16.779,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 16.779,
          end: 16.819,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "the",
          start: 16.819,
          end: 16.879,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 16.879,
          end: 16.959,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "world's",
          start: 16.959,
          end: 17.319,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 17.319,
          end: 17.34,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "population.",
          start: 17.34,
          end: 18.2,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 18.2,
          end: 19.379,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
      ],
    },
    {
      text: "If you're alive today with more health than illness you are more blessed than the million people that won't survive this week. And if you can read and understand this message ",
      words: [
        {
          text: "If",
          start: 19.379,
          end: 19.479,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 19.479,
          end: 19.539,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you're",
          start: 19.539,
          end: 19.68,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 19.68,
          end: 19.719,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "alive",
          start: 19.719,
          end: 20.14,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 20.14,
          end: 20.18,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "today",
          start: 20.18,
          end: 20.76,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 20.76,
          end: 21.279,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "with",
          start: 21.279,
          end: 21.46,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 21.46,
          end: 21.52,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "more",
          start: 21.52,
          end: 21.72,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 21.72,
          end: 21.799,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "health",
          start: 21.799,
          end: 22.139,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 22.139,
          end: 22.199,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "than",
          start: 22.199,
          end: 22.319,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 22.319,
          end: 22.34,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "illness",
          start: 22.34,
          end: 22.899,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 22.899,
          end: 23.739,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you",
          start: 23.739,
          end: 23.859,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 23.859,
          end: 23.879,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "are",
          start: 23.879,
          end: 23.979,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 23.979,
          end: 24.019,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "more",
          start: 24.019,
          end: 24.18,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 24.18,
          end: 24.279,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "blessed",
          start: 24.279,
          end: 24.68,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 24.68,
          end: 24.699,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "than",
          start: 24.699,
          end: 24.84,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 24.84,
          end: 24.859,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "the",
          start: 24.859,
          end: 24.94,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 24.94,
          end: 24.979,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "million",
          start: 24.979,
          end: 25.319,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 25.319,
          end: 25.439,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "people",
          start: 25.439,
          end: 25.76,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 25.76,
          end: 25.779,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "that",
          start: 25.779,
          end: 25.939,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 25.939,
          end: 26.0,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "won't",
          start: 26.0,
          end: 26.219,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 26.219,
          end: 26.26,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "survive",
          start: 26.26,
          end: 26.78,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 26.78,
          end: 26.799,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "this",
          start: 26.799,
          end: 27.019,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 27.019,
          end: 27.079,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "week.",
          start: 27.079,
          end: 27.479,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 27.479,
          end: 28.459,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "And",
          start: 28.459,
          end: 28.579,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 28.579,
          end: 28.599,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "if",
          start: 28.599,
          end: 28.699,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 28.699,
          end: 28.739,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "you",
          start: 28.739,
          end: 28.859,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 28.859,
          end: 28.879,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "can",
          start: 28.879,
          end: 29.019,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 29.019,
          end: 29.079,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "read",
          start: 29.079,
          end: 29.38,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 29.38,
          end: 29.399,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "and",
          start: 29.399,
          end: 29.52,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 29.52,
          end: 29.539,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "understand",
          start: 29.539,
          end: 30.18,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 30.18,
          end: 30.219,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "this",
          start: 30.219,
          end: 30.42,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 30.42,
          end: 30.479,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "message",
          start: 30.479,
          end: 30.959,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 30.959,
          end: 32.18,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
      ],
    },
    {
      text: "you are more fortunate than the 500 million people who cannot see, cannot read and cannot access the knowledge and information that surrounds us.",
      words: [
        {
          text: "you",
          start: 32.18,
          end: 32.299,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 32.299,
          end: 32.319,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "are",
          start: 32.319,
          end: 32.42,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 32.42,
          end: 32.439,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "more",
          start: 32.439,
          end: 32.619,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 32.619,
          end: 32.7,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "fortunate",
          start: 32.7,
          end: 33.279,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 33.279,
          end: 33.639,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "than",
          start: 33.639,
          end: 33.779,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 33.779,
          end: 33.799,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "the",
          start: 33.799,
          end: 33.92,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 33.92,
          end: 34.0,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "500",
          start: 34.0,
          end: 34.68,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 34.68,
          end: 34.759,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "million",
          start: 34.759,
          end: 35.139,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 35.139,
          end: 35.219,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "people",
          start: 35.219,
          end: 35.479,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 35.479,
          end: 35.5,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "who",
          start: 35.5,
          end: 35.62,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 35.62,
          end: 35.659,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "cannot",
          start: 35.659,
          end: 36.019,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 36.019,
          end: 36.159,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "see,",
          start: 36.159,
          end: 36.62,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 36.62,
          end: 37.159,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "cannot",
          start: 37.159,
          end: 37.499,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 37.499,
          end: 37.599,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "read",
          start: 37.599,
          end: 37.959,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 37.959,
          end: 37.979,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "and",
          start: 37.979,
          end: 38.159,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 38.159,
          end: 38.18,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "cannot",
          start: 38.18,
          end: 38.479,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 38.479,
          end: 38.5,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "access",
          start: 38.5,
          end: 39.059,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 39.059,
          end: 39.079,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "the",
          start: 39.079,
          end: 39.2,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 39.2,
          end: 39.259,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "knowledge",
          start: 39.259,
          end: 39.659,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 39.659,
          end: 39.659,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "and",
          start: 39.659,
          end: 39.779,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 39.779,
          end: 39.799,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "information",
          start: 39.799,
          end: 40.499,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 40.499,
          end: 40.52,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "that",
          start: 40.52,
          end: 40.679,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 40.679,
          end: 40.7,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "surrounds",
          start: 40.7,
          end: 41.199,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 41.199,
          end: 41.219,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "us.",
          start: 41.219,
          end: 41.58,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
      ],
    },
    {
      text: " Life is not for complaining about pain and sorrows.",
      words: [
        {
          text: " ",
          start: 41.58,
          end: 42.52,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "Life",
          start: 42.52,
          end: 42.899,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 42.899,
          end: 42.919,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "is",
          start: 42.919,
          end: 43.059,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 43.059,
          end: 43.099,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "not",
          start: 43.099,
          end: 43.319,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 43.319,
          end: 43.36,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "for",
          start: 43.36,
          end: 43.519,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 43.519,
          end: 43.54,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "complaining",
          start: 43.54,
          end: 44.18,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 44.18,
          end: 44.2,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "about",
          start: 44.2,
          end: 44.479,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 44.479,
          end: 44.599,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "pain",
          start: 44.599,
          end: 44.979,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 44.979,
          end: 44.979,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "and",
          start: 44.979,
          end: 45.119,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 45.119,
          end: 45.239,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "sorrows.",
          start: 45.239,
          end: 45.979,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
      ],
    },
    {
      text: " It's about prioritizing countless other reasons to be grateful for the privileges we often take for granted.",
      words: [
        {
          text: " ",
          start: 45.979,
          end: 46.7,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "It's",
          start: 46.7,
          end: 46.86,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 46.86,
          end: 46.879,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "about",
          start: 46.879,
          end: 47.159,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 47.159,
          end: 47.219,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "prioritizing",
          start: 47.219,
          end: 48.279,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 48.279,
          end: 48.299,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "countless",
          start: 48.299,
          end: 48.759,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 48.759,
          end: 48.779,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "other",
          start: 48.779,
          end: 48.959,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 48.959,
          end: 49.039,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "reasons",
          start: 49.039,
          end: 49.519,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 49.519,
          end: 49.539,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "to",
          start: 49.539,
          end: 49.639,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 49.639,
          end: 49.659,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "be",
          start: 49.659,
          end: 49.799,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 49.799,
          end: 49.799,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "grateful",
          start: 49.799,
          end: 50.22,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 50.22,
          end: 50.259,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "for",
          start: 50.259,
          end: 50.36,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 50.36,
          end: 50.36,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "the",
          start: 50.36,
          end: 50.499,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 50.499,
          end: 50.5,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "privileges",
          start: 50.5,
          end: 51.079,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 51.079,
          end: 51.099,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "we",
          start: 51.099,
          end: 51.24,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 51.24,
          end: 51.259,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "often",
          start: 51.259,
          end: 51.54,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 51.54,
          end: 51.619,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "take",
          start: 51.619,
          end: 51.84,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 51.84,
          end: 51.86,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "for",
          start: 51.86,
          end: 51.959,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
        {
          text: " ",
          start: 51.959,
          end: 52.02,
          type: "spacing",
          logprob: 0.0,
          characters: null,
        },
        {
          text: "granted.",
          start: 52.02,
          end: 52.579,
          type: "word",
          logprob: 0.0,
          characters: null,
        },
      ],
    },
  ],
}
